---
failure-threshold: error
ignored:
  - DL3018 # Pin versions in apk add.
  - DL3022 # COPY --from alias
label-schema:
 org.opencontainers.image.authors: text
 org.opencontainers.image.source: url
 org.opencontainers.image.description: text
 org.opencontainers.image.licenses: text
strict-labels: true
