FROM registry.access.redhat.com/ubi8/ubi:latest

LABEL maintainer "Franklin D <frank378@gmail.com>"

WORKDIR /workspace
ENV MY_DIR /workspace
COPY . ${MY_DIR}

RUN \
  yum -y update; \
  yum -y install make gcc automake autoconf gnupg2 wget xz; \
  yum install openssl-devel libffi-devel bzip2-devel -y; \
  wget https://www.python.org/ftp/python/3.10.5/Python-3.10.5.tar.xz; \
  unxz Python-3.10.5.tar.xz; \
  tar xf Python-3.10.5.tar; \
  cd Python-3.10.5; \
  sed -i 's/PKG_CONFIG openssl /PKG_CONFIG openssl11 /g' configure; \
  ./configure --enable-optimizations; \
  make install  
# make altinstall to leave original 3.6

# install latest pip with new Python 3.10.x
RUN \
  if [ ! -d "${MY_DIR}/build" ]; then mkdir ${MY_DIR}/build; fi; \
  cd ${MY_DIR}/build && wget https://bootstrap.pypa.io/get-pip.py; \
  /usr/local/bin/python3 ${MY_DIR}/build/get-pip.py

# install requirements from our project
RUN \
  /usr/local/bin/python3 -m pip install six; \
  /usr/local/bin/python3 -m pip install -r${MY_DIR}/src/requirements.txt

RUN \
  /usr/local/bin/python3 -m pip install tox; \
  /usr/local/bin/python3 -m pip install -r${MY_DIR}/tests/requirements-security.txt; \
  /usr/local/bin/python3 -m pip install -r${MY_DIR}/tests/requirements-test.txt; \
  tox -e py310
  